name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print API Key
        run: echo "API_KEY=$API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
